#!/usr/bin/env python3
"""Build CatalogData.lua from Talent.sql + SkillLineAbility.sql."""

import re
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
DMLS = ROOT / "apps/patchgenerator/dmls/required"
OUT = Path(__file__).resolve().parent / "CatalogData.lua"

# DBC class id -> spec id string -> SkillLine id
SPEC_SKILLS = {
    6: {"blood": 770, "frost": 771, "unholy": 772},
    11: {"balance": 574, "feral": 134, "resto": 573},
    3: {"bm": 50, "marks": 163, "survival": 51},
    8: {"arcane": 237, "fire": 8, "frost": 6},
    2: {"holy": 56, "prot": 267, "ret": 184},
    5: {"disc": 613, "holy": 594, "shadow": 78},
    4: {"assassination": 253, "combat": 38, "subtlety": 39},
    7: {"elemental": 375, "enhancement": 373, "resto": 374},
    9: {"affliction": 355, "demonology": 354, "destruction": 593},
    1: {"arms": 26, "fury": 256, "prot": 257},
}

SKILL_TO_SPEC = {}
for class_id, specs in SPEC_SKILLS.items():
    for spec_id, skill in specs.items():
        SKILL_TO_SPEC[skill] = (class_id, spec_id)

TUPLE_RE = re.compile(r"\(([^()]+)\)")


def parse_tuples(path: Path):
    text = path.read_text(encoding="utf-8", errors="replace")
    rows = []
    for m in TUPLE_RE.finditer(text):
        parts = [p.strip() for p in m.group(1).split(",")]
        try:
            rows.append([int(p) for p in parts])
        except ValueError:
            continue
    return rows


def lua_list(nums):
    return "{" + ",".join(str(n) for n in nums) + "}"


def main():
    talent_rows = parse_tuples(DMLS / "Talent.sql")
    sla_rows = parse_tuples(DMLS / "SkillLineAbility.sql")

    talent_spell_ids = set()
    talents = defaultdict(list)
    for row in talent_rows:
        if len(row) < 23:
            continue
        tid, tab, tier, col = row[0], row[1], row[2], row[3]
        ranks = [x for x in row[4:13] if x]
        if not ranks:
            continue
        for sid in ranks:
            talent_spell_ids.add(sid)
        prereq = row[13] or 0
        prereq_rank = row[16] or 0
        talents[tab].append(
            {
                "id": tid,
                "t": tier,
                "c": col,
                "r": ranks,
                "p": prereq,
                "pr": prereq_rank,
            }
        )

    spells = defaultdict(lambda: defaultdict(list))
    seen = defaultdict(set)
    for row in sla_rows:
        if len(row) < 3:
            continue
        skill, spell = row[1], row[2]
        if spell <= 0 or spell in talent_spell_ids:
            continue
        mapped = SKILL_TO_SPEC.get(skill)
        if not mapped:
            continue
        class_id, spec_id = mapped
        if spell in seen[(class_id, spec_id)]:
            continue
        seen[(class_id, spec_id)].add(spell)
        spells[class_id][spec_id].append(spell)

    for class_id in spells:
        for spec_id in spells[class_id]:
            spells[class_id][spec_id].sort()

    lines = [
        "-- Generated by generate_catalog.py. Do not edit by hand.",
        "local C = ClasslessUICatalog",
        "if not C then return end",
        "C.spells = {",
    ]
    for class_id in sorted(spells):
        lines.append(f"  [{class_id}] = {{")
        for spec_id in sorted(spells[class_id]):
            ids = spells[class_id][spec_id]
            lines.append(f"    {spec_id} = {lua_list(ids)},")
        lines.append("  },")
    lines.append("}")
    lines.append("C.talents = {")
    for tab in sorted(talents):
        lines.append(f"  [{tab}] = {{")
        nodes = sorted(talents[tab], key=lambda n: (n["t"], n["c"], n["id"]))
        for n in nodes:
            lines.append(
                "    {id=%d,t=%d,c=%d,r=%s,p=%d,pr=%d},"
                % (n["id"], n["t"], n["c"], lua_list(n["r"]), n["p"], n["pr"])
            )
        lines.append("  },")
    lines.append("}")
    lines.append("C.petTabs = {409,410,411}")
    lines.append("C.spellSet = {}")
    lines.append("for classId, specs in pairs(C.spells) do")
    lines.append("  for specId, ids in pairs(specs) do")
    lines.append("    for i = 1, #ids do C.spellSet[ids[i]] = true end")
    lines.append("  end")
    lines.append("end")
    lines.append("C.talentById = {}")
    lines.append("for tabId, nodes in pairs(C.talents) do")
    lines.append("  for i = 1, #nodes do")
    lines.append("    local n = nodes[i]")
    lines.append("    n.tabId = tabId")
    lines.append("    C.talentById[n.id] = n")
    lines.append("  end")
    lines.append("end")
    lines.append("")
    lines.append("local AIO = AIO or require(\"AIO\")")
    lines.append("if AIO.IsMainState and AIO.IsMainState() and AIO.AddAddon then")
    lines.append("  AIO.AddAddon()")
    lines.append("end")
    lines.append("")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    n_spells = sum(len(ids) for specs in spells.values() for ids in specs.values())
    n_talents = sum(len(v) for v in talents.values())
    print(f"wrote {OUT} spells={n_spells} talent_nodes={n_talents}")


if __name__ == "__main__":
    main()
