#!/usr/bin/env python3
"""Build CatalogData.lua from Talent.sql, SkillLineAbility.sql, and live class trainers.

Spellbook entries are restricted to spells class trainers actually teach
(acore_world.trainer_spell for trainer.Type = 0). SkillLineAbility is only
used to place a trainer spell into a spec. Talent trees stay Talent.dbc.
"""

import re
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
DMLS = ROOT / "apps/patchgenerator/dmls/required"
OUT = Path(__file__).resolve().parent / "CatalogData.lua"

# DBC class id -> spec id string -> SkillLine id
SPEC_SKILLS = {
    6: {"blood": 770, "frost": 771, "unholy": 772},
    11: {"balance": 574, "feral": 134, "resto": 573},
    3: {"bm": 50, "marks": 163, "survival": 51},
    8: {"arcane": 237, "fire": 8, "frost": 6},
    2: {"holy": 56, "prot": 267, "ret": 184},
    5: {"disc": 613, "holy": 594, "shadow": 78},
    4: {"assassination": 253, "combat": 38, "subtlety": 39},
    7: {"elemental": 375, "enhancement": 373, "resto": 374},
    9: {"affliction": 355, "demonology": 354, "destruction": 593},
    1: {"arms": 26, "fury": 256, "prot": 257},
}

SKILL_TO_SPEC = {}
for class_id, specs in SPEC_SKILLS.items():
    for spec_id, skill in specs.items():
        SKILL_TO_SPEC[skill] = (class_id, spec_id)

# Triggered/effect spells that share a player spell name (not real ranks).
BLOCKED_SPELLS = {
    42651,  # Army of the Dead summon trigger
}

# creature_default_trainer / trainer.Id -> ChrClasses id (Type=0 class trainers).
TRAINER_TO_CLASS = {
    1: 1, 2: 1,  # Warrior
    3: 2, 4: 2, 5: 2, 6: 2,  # Paladin
    7: 3, 8: 3,  # Hunter
    9: 4, 10: 4,  # Rogue
    11: 5, 12: 5,  # Priest
    13: 6,  # Death Knight
    14: 7, 15: 7,  # Shaman
    16: 8, 17: 8,  # Mage
    31: 9, 32: 9,  # Warlock
    33: 11, 34: 11,  # Druid
}

TUPLE_RE = re.compile(r"\(([^()]+)\)")


def parse_tuples(path: Path):
    text = path.read_text(encoding="utf-8", errors="replace")
    rows = []
    for m in TUPLE_RE.finditer(text):
        parts = [p.strip() for p in m.group(1).split(",")]
        try:
            rows.append([int(p) for p in parts])
        except ValueError:
            continue
    return rows


def lua_list(nums):
    return "{" + ",".join(str(n) for n in nums) + "}"


def load_trainer_spells(path: Path):
    by_class = defaultdict(set)
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line:
            continue
        parts = line.split()
        if len(parts) < 2:
            continue
        trainer_id, spell = int(parts[0]), int(parts[1])
        class_id = TRAINER_TO_CLASS.get(trainer_id)
        if not class_id or spell in BLOCKED_SPELLS:
            continue
        by_class[class_id].add(spell)
    return by_class


def main():
    talent_rows = parse_tuples(DMLS / "Talent.sql")
    sla_rows = parse_tuples(DMLS / "SkillLineAbility.sql")

    talent_spell_ids = set()
    talents = defaultdict(list)
    for row in talent_rows:
        if len(row) < 23:
            continue
        tid, tab, tier, col = row[0], row[1], row[2], row[3]
        ranks = [x for x in row[4:13] if x]
        if not ranks:
            continue
        for sid in ranks:
            talent_spell_ids.add(sid)
        prereq = row[13] or 0
        prereq_rank = row[16] or 0
        talents[tab].append(
            {
                "id": tid,
                "t": tier,
                "c": col,
                "r": ranks,
                "p": prereq,
                "pr": prereq_rank,
            }
        )

    trainer_by_class = load_trainer_spells(Path(__file__).resolve().parent / "class_trainer_spells.txt")
    trainer_all = set()
    for s in trainer_by_class.values():
        trainer_all |= s

    # Skill line -> spec, but only for spells a class trainer actually sells.
    spells = defaultdict(lambda: defaultdict(list))
    placed = defaultdict(set)
    for row in sla_rows:
        if len(row) < 3:
            continue
        skill, spell = row[1], row[2]
        if spell <= 0 or spell in BLOCKED_SPELLS:
            continue
        mapped = SKILL_TO_SPEC.get(skill)
        if not mapped:
            continue
        class_id, spec_id = mapped
        if spell not in trainer_by_class.get(class_id, ()):
            continue
        if spell in placed[class_id]:
            continue
        placed[class_id].add(spell)
        spells[class_id][spec_id].append(spell)

    for class_id, trained in trainer_by_class.items():
        leftover = sorted(trained - placed[class_id] - BLOCKED_SPELLS)
        for spell in leftover:
            spells[class_id]["general"].append(spell)
            placed[class_id].add(spell)

    for class_id in spells:
        for spec_id in spells[class_id]:
            spells[class_id][spec_id].sort()

    lines = [
        "-- Generated by generate_catalog.py. Do not edit by hand.",
        "local C = ClasslessUICatalog",
        "if not C then return end",
        "C.spells = {",
    ]
    for class_id in sorted(spells):
        lines.append(f"  [{class_id}] = {{")
        for spec_id in sorted(spells[class_id]):
            ids = spells[class_id][spec_id]
            lines.append(f"    {spec_id} = {lua_list(ids)},")
        lines.append("  },")
    lines.append("}")
    lines.append("C.talents = {")
    for tab in sorted(talents):
        lines.append(f"  [{tab}] = {{")
        nodes = sorted(talents[tab], key=lambda n: (n["t"], n["c"], n["id"]))
        for n in nodes:
            lines.append(
                "    {id=%d,t=%d,c=%d,r=%s,p=%d,pr=%d},"
                % (n["id"], n["t"], n["c"], lua_list(n["r"]), n["p"], n["pr"])
            )
        lines.append("  },")
    lines.append("}")
    lines.append("C.petTabs = {409,410,411}")
    lines.append("C.spellSet = {}")
    lines.append("for classId, specs in pairs(C.spells) do")
    lines.append("  for specId, ids in pairs(specs) do")
    lines.append("    local kept = {}")
    lines.append("    for i = 1, #ids do")
    lines.append("      local sid = ids[i]")
    lines.append("      if not (C.blockedSpells and C.blockedSpells[sid]) then")
    lines.append("        kept[#kept + 1] = sid")
    lines.append("        C.spellSet[sid] = true")
    lines.append("      end")
    lines.append("    end")
    lines.append("    C.spells[classId][specId] = kept")
    lines.append("  end")
    lines.append("end")
    lines.append("C.talentById = {}")
    lines.append("for tabId, nodes in pairs(C.talents) do")
    lines.append("  for i = 1, #nodes do")
    lines.append("    local n = nodes[i]")
    lines.append("    n.tabId = tabId")
    lines.append("    C.talentById[n.id] = n")
    lines.append("  end")
    lines.append("end")
    lines.append("")
    lines.append("local AIO = AIO or require(\"AIO\")")
    lines.append("if AIO.IsMainState and AIO.IsMainState() and AIO.AddAddon then")
    lines.append("  AIO.AddAddon()")
    lines.append("end")
    lines.append("")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    n_spells = sum(len(ids) for specs in spells.values() for ids in specs.values())
    n_talents = sum(len(v) for v in talents.values())
    print(f"wrote {OUT} spells={n_spells} talent_nodes={n_talents}")


if __name__ == "__main__":
    main()
