-- Movement spell removed on entering combat and castable out of combat
-- insert into spell
-- values (id=3600001,category=1, dispel_type=0, mechanic=0, attributes=276824080,
--           attributes_ex=32, attributes_ex_b=16, attributes_ex_c=0, attributes_ex_d=0,
--         attributes_ex_e=0, attributes_ex_f=0, attributes_ex_g=0, shapeshift_mask_0=-1,
--         shapeshift_mask_1=-1, shapeshift_exclude_0=0, shapeshift_exclude_1=0, targets=2,
--         target_creature_type=-1, requires_spell_focus=0, facing_caster_flags=0, caster_aura_state=0,
--         target_aura_state=0, exclude_caster_aura_state=0,exclude_target_aura_state=0,
--         caster_aura_spell=0, target_aura_spell=0,exclude_caster_aura_spell=0, exclude_target_aura_spell,
--         casting_time_index=1, recovery_time=0, category_recovery_time=0,interrupt_flags=0,
--         aura_interrupt_flags=8400898, channel_interrupt_flags=0,proc_type_mask=0,
--         proc_chance=101, proc_charges=0, max_level=0, base_level=1,
--         spell_level=1, duration_index=21, power_type=3, mana_cost=0, mana_cost_per_level=0,
--         mana_per_second=0, mana_per_second_per_level=0,range_index=1, speed=0,
--         modal_next_spell=0, cumulative_aura=0,
--         totem_0=0, totem_1=0,
--         reagent_0=0,reagent_1=0, reagent_2=0,
--         reagent_3=0,reagent_4=0,reagent_5=0,reagent_6=0,reagent_7=0,
--         reagent_count_0=0,reagent_count_1=0, reagent_count_2,reagent_count_3=0,
--         reagent_count_4=0,reagent_count_5=0,reagent_count_6=0,reagent_count_7=0,
--         equipped_item_class=-1, equipped_item_subclass=0, equipped_item_inv_types=0, equipped_item_inv_types=0,
--         effect_0=6,effect_1=0, effect_2=0,
--         effect_die_sides_0=1,effect_die_sides_1=0,effect_die_sides_2=0,
--         effect_real_points_per_level_0=0, effect_real_points_per_level_1=0, effect_real_points_per_level_2,
--         effect_base_points_0=149,effect_base_points_1=0, effect_base_points_2=0,
--         effect_mechanic_0=0,effect_mechanic_1=0, effect_mechanic_2=0,
--         implicit_target_a_0=1, implicit_target_a_1=0,implicit_target_a_2=0,
--         implicit_target_b_0=0, implicit_target_b_1=0,implicit_target_b_2=0,
--         effect_radius_index_0=0, effect_radius_index_1=0, effect_radius_index_2,
--         effect_aura_0=31, effect_aura_1=0, effect_aura_2=0,
--         effect_aura_period_0, effect_aura_period_1=0, effect_aura_period_2=0,
--         effect_amplitude_0=0,effect_amplitude_1=0,effect_amplitude_2=0,
--         effect_chain_targets_0=0,effect_chain_targets_1=0,effect_chain_targets_2=0,
--         effect_item_type_0=0,effect_item_type_1=0,effect_item_type_2=0,
--         effect_misc_value_0=0, effect_misc_value_1=0, effect_misc_value_2=0,
--         effect_misc_value_b_0=0, effect_misc_value_b_1=0, effect_misc_value_b_2=0,
--         effect_trigger_spell_0=0, effect_trigger_spell_1=0, effect_trigger_spell_2=0,
--         effect_points_per_combo_0=0,effect_points_per_combo_1=0,effect_points_per_combo_2=0,
--         effect_spell_class_mask_a_0=0,effect_spell_class_mask_a_1=0,effect_spell_class_mask_a_2=0,
--         effect_spell_class_mask_b_0=0,effect_spell_class_mask_b_1=0,effect_spell_class_mask_b_2=0,
--         effect_spell_class_mask_c_0=0,effect_spell_class_mask_c_1=0,effect_spell_class_mask_c_2=0,
--         spell_visual_id_0=0,spell_icon_id=516,active_icon_id=0,spell_priority=0,
--         name_lang_en_gb='Gas Gas Gas!',name_lang_ko_kr='',name_lang_fr_fr='',
--         name_lang_de_de='',name_lang_en_cn='',name_lang_en_tw='',name_lang_es_es='',
--         name_lang_es_mx='',name_lang_ru_ru='',name_lang_ja_jp='',name_lang_pt_pt='',
--         name_lang_it_it='',name_lang_unknown_12='',name_lang_unknown_13='',
--         name_lang_unknown_14='',name_lang_unknown_15='',name_lang_flags=16712190,
--         name_subtext_lang_en_gb    = '',
--         name_subtext_lang_ko_kr    = '',
--         name_subtext_lang_fr_fr    = '',
--         name_subtext_lang_de_de    = '',
--         name_subtext_lang_en_cn    = '',
--         name_subtext_lang_en_tw    = '',
--         name_subtext_lang_es_es    = '',
--         name_subtext_lang_es_mx    = '',
--         name_subtext_lang_ru_ru    = '',
--         name_subtext_lang_ja_jp    = '',
--         name_subtext_lang_pt_pt    = '',
--         name_subtext_lang_it_it    = '',
--         name_subtext_lang_unknown_12 = '',
--         name_subtext_lang_unknown_13 = '',
--         name_subtext_lang_unknown_14 = '',
--         name_subtext_lang_unknown_15 = '',
--         name_subtext_lang_flags    = 16712190,
--
--         description_lang_en_gb     = 'Increases your movement speed by $s1%. Breaks on entering combat.',
--         description_lang_ko_kr     = '',
--         description_lang_fr_fr     = '',
--         description_lang_de_de     = '',
--         description_lang_en_cn     = '',
--         description_lang_en_tw     = '',
--         description_lang_es_es     = '',
--         description_lang_es_mx     = '',
--         description_lang_ru_ru     = '',
--         description_lang_ja_jp     = '',
--         description_lang_pt_pt     = '',
--         description_lang_it_it     = '',
--         description_lang_unknown_12 = '',
--         description_lang_unknown_13 = '',
--         description_lang_unknown_14 = '',
--         description_lang_unknown_15 = '',
--         description_lang_flags     = 16712190,
--         aura_description_lang_en_gb      = 'Movement speed increased by $s1%. Breaks on entering combat.',
--         aura_description_lang_ko_kr      = '',
--         aura_description_lang_fr_fr      = '',
--         aura_description_lang_de_de      = '',
--         aura_description_lang_en_cn      = '',
--         aura_description_lang_en_tw      = '',
--         aura_description_lang_es_es      = '',
--         aura_description_lang_es_mx      = '',
--         aura_description_lang_ru_ru      = '',
--         aura_description_lang_ja_jp      = '',
--         aura_description_lang_pt_pt      = '',
--         aura_description_lang_it_it      = '',
--         aura_description_lang_unknown_12 = '',
--         aura_description_lang_unknown_13 = '',
--         aura_description_lang_unknown_14 = '',
--         aura_description_lang_unknown_15 = '',
--         aura_description_lang_flags      = 16712190,
--         mana_cost_pct=0, start_recovery_category=0, start_recovery_time=0,
--         max_target_level=0,spell_class_set=0,
--         spell_class_mask_0=0, spell_class_mask_1=0, spell_class_mask_2=0,
--         max_targets=0,defense_type=0,prevention_type=0, stance_bar_order=0,
--         effect_chain_amplitude_0=1, effect_chain_amplitude_1=1, effect_chain_amplitude_2=1,
--         min_faction_id=0, min_reputation=0, required_aura_vision=0,
--         required_totem_category_id_0=0,required_totem_category_id_1=0,required_areas_id=0,
--         school_mask=0, rune_cost_id=0, spell_missile_id=0,power_display_id=0,
--         effect_bonus_coefficient_0=0,effect_bonus_coefficient_1=0,effect_bonus_coefficient_2=0,
--         description_variables_id=0,difficulty=0);

-- ... existing code ...
-- Movement spell removed on entering combat and castable out of combat
INSERT INTO spell (
    id,
    category,
    dispel_type,
    mechanic,
    attributes,
    attributes_ex,
    attributes_ex_b,
    attributes_ex_c,
    attributes_ex_d,
    attributes_ex_e,
    attributes_ex_f,
    attributes_ex_g,
    shapeshift_mask_0,
    shapeshift_mask_1,
    shapeshift_exclude_0,
    shapeshift_exclude_1,
    targets,
    target_creature_type,
    requires_spell_focus,
    facing_caster_flags,
    caster_aura_state,
    target_aura_state,
    exclude_caster_aura_state,
    exclude_target_aura_state,
    caster_aura_spell,
    target_aura_spell,
    exclude_caster_aura_spell,
    exclude_target_aura_spell,
    casting_time_index,
    recovery_time,
    category_recovery_time,
    interrupt_flags,
    aura_interrupt_flags,
    channel_interrupt_flags,
    proc_type_mask,
    proc_chance,
    proc_charges,
    max_level,
    base_level,
    spell_level,
    duration_index,
    power_type,
    mana_cost,
    mana_cost_per_level,
    mana_per_second,
    mana_per_second_per_level,
    range_index,
    speed,
    modal_next_spell,
    cumulative_aura,
    totem_0,
    totem_1,
    reagent_0,
    reagent_1,
    reagent_2,
    reagent_3,
    reagent_4,
    reagent_5,
    reagent_6,
    reagent_7,
    reagent_count_0,
    reagent_count_1,
    reagent_count_2,
    reagent_count_3,
    reagent_count_4,
    reagent_count_5,
    reagent_count_6,
    reagent_count_7,
    equipped_item_class,
    equipped_item_subclass,
    equipped_item_inv_types,
    effect_0,
    effect_1,
    effect_2,
    effect_die_sides_0,
    effect_die_sides_1,
    effect_die_sides_2,
    effect_real_points_per_level_0,
    effect_real_points_per_level_1,
    effect_real_points_per_level_2,
    effect_base_points_0,
    effect_base_points_1,
    effect_base_points_2,
    effect_mechanic_0,
    effect_mechanic_1,
    effect_mechanic_2,
    implicit_target_a_0,
    implicit_target_a_1,
    implicit_target_a_2,
    implicit_target_b_0,
    implicit_target_b_1,
    implicit_target_b_2,
    effect_radius_index_0,
    effect_radius_index_1,
    effect_radius_index_2,
    effect_aura_0,
    effect_aura_1,
    effect_aura_2,
    effect_aura_period_0,
    effect_aura_period_1,
    effect_aura_period_2,
    effect_amplitude_0,
    effect_amplitude_1,
    effect_amplitude_2,
    effect_chain_targets_0,
    effect_chain_targets_1,
    effect_chain_targets_2,
    effect_item_type_0,
    effect_item_type_1,
    effect_item_type_2,
    effect_misc_value_0,
    effect_misc_value_1,
    effect_misc_value_2,
    effect_misc_value_b_0,
    effect_misc_value_b_1,
    effect_misc_value_b_2,
    effect_trigger_spell_0,
    effect_trigger_spell_1,
    effect_trigger_spell_2,
    effect_points_per_combo_0,
    effect_points_per_combo_1,
    effect_points_per_combo_2,
    effect_spell_class_mask_a_0,
    effect_spell_class_mask_a_1,
    effect_spell_class_mask_a_2,
    effect_spell_class_mask_b_0,
    effect_spell_class_mask_b_1,
    effect_spell_class_mask_b_2,
    effect_spell_class_mask_c_0,
    effect_spell_class_mask_c_1,
    effect_spell_class_mask_c_2,
    spell_visual_id_0,
    spell_visual_id_1,
    spell_icon_id,
    active_icon_id,
    spell_priority,
    name_lang_en_gb,
    name_lang_ko_kr,
    name_lang_fr_fr,
    name_lang_de_de,
    name_lang_en_cn,
    name_lang_en_tw,
    name_lang_es_es,
    name_lang_es_mx,
    name_lang_ru_ru,
    name_lang_ja_jp,
    name_lang_pt_pt,
    name_lang_it_it,
    name_lang_unknown_12,
    name_lang_unknown_13,
    name_lang_unknown_14,
    name_lang_unknown_15,
    name_lang_flags,
    name_subtext_lang_en_gb,
    name_subtext_lang_ko_kr,
    name_subtext_lang_fr_fr,
    name_subtext_lang_de_de,
    name_subtext_lang_en_cn,
    name_subtext_lang_en_tw,
    name_subtext_lang_es_es,
    name_subtext_lang_es_mx,
    name_subtext_lang_ru_ru,
    name_subtext_lang_ja_jp,
    name_subtext_lang_pt_pt,
    name_subtext_lang_it_it,
    name_subtext_lang_unknown_12,
    name_subtext_lang_unknown_13,
    name_subtext_lang_unknown_14,
    name_subtext_lang_unknown_15,
    name_subtext_lang_flags,
    description_lang_en_gb,
    description_lang_ko_kr,
    description_lang_fr_fr,
    description_lang_de_de,
    description_lang_en_cn,
    description_lang_en_tw,
    description_lang_es_es,
    description_lang_es_mx,
    description_lang_ru_ru,
    description_lang_ja_jp,
    description_lang_pt_pt,
    description_lang_it_it,
    description_lang_unknown_12,
    description_lang_unknown_13,
    description_lang_unknown_14,
    description_lang_unknown_15,
    description_lang_flags,
    aura_description_lang_en_gb,
    aura_description_lang_ko_kr,
    aura_description_lang_fr_fr,
    aura_description_lang_de_de,
    aura_description_lang_en_cn,
    aura_description_lang_en_tw,
    aura_description_lang_es_es,
    aura_description_lang_es_mx,
    aura_description_lang_ru_ru,
    aura_description_lang_ja_jp,
    aura_description_lang_pt_pt,
    aura_description_lang_it_it,
    aura_description_lang_unknown_12,
    aura_description_lang_unknown_13,
    aura_description_lang_unknown_14,
    aura_description_lang_unknown_15,
    aura_description_lang_flags,
    mana_cost_pct,
    start_recovery_category,
    start_recovery_time,
    max_target_level,
    spell_class_set,
    spell_class_mask_0,
    spell_class_mask_1,
    spell_class_mask_2,
    max_targets,
    defense_type,
    prevention_type,
    stance_bar_order,
    effect_chain_amplitude_0,
    effect_chain_amplitude_1,
    effect_chain_amplitude_2,
    min_faction_id,
    min_reputation,
    required_aura_vision,
    required_totem_category_id_0,
    required_totem_category_id_1,
    required_areas_id,
    school_mask,
    rune_cost_id,
    spell_missile_id,
    power_display_id,
    effect_bonus_coefficient_0,
    effect_bonus_coefficient_1,
    effect_bonus_coefficient_2,
    description_variables_id,
    difficulty
)
VALUES (
           360001, 1, 0, 0, 276824080,
           32, 0, 0, 0, 0, 0, 0,
           0, 0, 0, 0, 0, -1, 0, 0,
           0, 0, 0, 0, 0, 0, 0, 0,
           1, 0, 0, 0, 8400898, 0,
           0, 101, 0, 0, 1, 1,
           21, 3, 0, 0, 0, 0,
           1, 0, 0, 0,
           0, 0,
           0, 0, 0, 0, 0, 0, 0, 0,
           0, 0, 0, 0, 0, 0, 0, 0,
           -1, 0, 0,
           6, 0, 0,
           1, 0, 0,
           0, 0, 0,
           149, 0, 0,
           0, 0, 0,
           1, 0, 0,
           0, 0, 0,
           0, 0, 0,
           31, 0, 0,
           0, 0, 0,
           0, 0, 0,
           0, 0, 0,
           0, 0, 0,
           0, 0, 0,
           0, 0, 0,
           0, 0, 0,
           0, 0, 0,
        0,0,0,
        0,0,0,
        0,0,0,
           6, 0,516, 0, 0,
           'Gas Gas Gas!', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
           16712190,
            '','','','','',
        '','','','','',
        '','','','','',
        '',16712190,
           'Increases your movement speed by $s1%. Breaks on entering combat.',
        '','','','','','','',
        '','','','','','','',
        '',16712190,
           'Movement speed increased by $s1%. Breaks on entering combat.','','','','',
        '','','','','','','',
        '','','','',
           16712190,
           0, 0, 0, 0, 0,
           0, 0, 0, 0, 0, 0, 0,
           1, 1, 1,
           0, 0, 0,
           0, 0, 0,
           0, 0, 0, 0,
           0, 0, 0,
           0, 0
       );
--
-- delete from spell where id = 360001;
-- select * from Spell where name_lang_en_gb = 'Gas Gas Gas!';

-- select sl.id,sl.display_name_lang_en_gb,srci.race_mask,srci.class_mask from SkillLine sl
-- join SkillRaceClassInfo srci on sl.id=srci.skill_id;

-- select sl.id,sl.category_id,sl.display_name_lang_en_gb, s.name_lang_en_gb, sla.*
-- from SkillLine sl
-- join SkillLineAbility sla on sl.id=sla.skill_line
-- join spell s on sla.spell=s.id
-- where sl.id = 183;
--
-- select * from SkillLineAbility;

insert into SkillLineAbility (id,skill_line,spell,race_mask,class_mask,exclude_race,exclude_class,min_skill_line_rank,superceded_by_spell,acquire_method,trivial_skill_line_rank_high,trivial_skill_line_rank_low,character_points_0,character_points_1)
values (21981,183,360001,-1,-1,0,0,0,0,2,0,0,0,0);

-- Atrain tele
-- effect_aura_0 = 17

INSERT INTO spell (
    id,
    category,
    dispel_type,
    mechanic,
    attributes,
    attributes_ex,
    attributes_ex_b,
    attributes_ex_c,
    attributes_ex_d,
    attributes_ex_e,
    attributes_ex_f,
    attributes_ex_g,
    shapeshift_mask_0,
    shapeshift_mask_1,
    shapeshift_exclude_0,
    shapeshift_exclude_1,
    targets,
    target_creature_type,
    requires_spell_focus,
    facing_caster_flags,
    caster_aura_state,
    target_aura_state,
    exclude_caster_aura_state,
    exclude_target_aura_state,
    caster_aura_spell,
    target_aura_spell,
    exclude_caster_aura_spell,
    exclude_target_aura_spell,
    casting_time_index,
    recovery_time,
    category_recovery_time,
    interrupt_flags,
    aura_interrupt_flags,
    channel_interrupt_flags,
    proc_type_mask,
    proc_chance,
    proc_charges,
    max_level,
    base_level,
    spell_level,
    duration_index,
    power_type,
    mana_cost,
    mana_cost_per_level,
    mana_per_second,
    mana_per_second_per_level,
    range_index,
    speed,
    modal_next_spell,
    cumulative_aura,
    totem_0,
    totem_1,
    reagent_0,
    reagent_1,
    reagent_2,
    reagent_3,
    reagent_4,
    reagent_5,
    reagent_6,
    reagent_7,
    reagent_count_0,
    reagent_count_1,
    reagent_count_2,
    reagent_count_3,
    reagent_count_4,
    reagent_count_5,
    reagent_count_6,
    reagent_count_7,
    equipped_item_class,
    equipped_item_subclass,
    equipped_item_inv_types,
    effect_0,
    effect_1,
    effect_2,
    effect_die_sides_0,
    effect_die_sides_1,
    effect_die_sides_2,
    effect_real_points_per_level_0,
    effect_real_points_per_level_1,
    effect_real_points_per_level_2,
    effect_base_points_0,
    effect_base_points_1,
    effect_base_points_2,
    effect_mechanic_0,
    effect_mechanic_1,
    effect_mechanic_2,
    implicit_target_a_0,
    implicit_target_a_1,
    implicit_target_a_2,
    implicit_target_b_0,
    implicit_target_b_1,
    implicit_target_b_2,
    effect_radius_index_0,
    effect_radius_index_1,
    effect_radius_index_2,
    effect_aura_0,
    effect_aura_1,
    effect_aura_2,
    effect_aura_period_0,
    effect_aura_period_1,
    effect_aura_period_2,
    effect_amplitude_0,
    effect_amplitude_1,
    effect_amplitude_2,
    effect_chain_targets_0,
    effect_chain_targets_1,
    effect_chain_targets_2,
    effect_item_type_0,
    effect_item_type_1,
    effect_item_type_2,
    effect_misc_value_0,
    effect_misc_value_1,
    effect_misc_value_2,
    effect_misc_value_b_0,
    effect_misc_value_b_1,
    effect_misc_value_b_2,
    effect_trigger_spell_0,
    effect_trigger_spell_1,
    effect_trigger_spell_2,
    effect_points_per_combo_0,
    effect_points_per_combo_1,
    effect_points_per_combo_2,
    effect_spell_class_mask_a_0,
    effect_spell_class_mask_a_1,
    effect_spell_class_mask_a_2,
    effect_spell_class_mask_b_0,
    effect_spell_class_mask_b_1,
    effect_spell_class_mask_b_2,
    effect_spell_class_mask_c_0,
    effect_spell_class_mask_c_1,
    effect_spell_class_mask_c_2,
    spell_visual_id_0,
    spell_visual_id_1,
    spell_icon_id,
    active_icon_id,
    spell_priority,
    name_lang_en_gb,
    name_lang_ko_kr,
    name_lang_fr_fr,
    name_lang_de_de,
    name_lang_en_cn,
    name_lang_en_tw,
    name_lang_es_es,
    name_lang_es_mx,
    name_lang_ru_ru,
    name_lang_ja_jp,
    name_lang_pt_pt,
    name_lang_it_it,
    name_lang_unknown_12,
    name_lang_unknown_13,
    name_lang_unknown_14,
    name_lang_unknown_15,
    name_lang_flags,
    name_subtext_lang_en_gb,
    name_subtext_lang_ko_kr,
    name_subtext_lang_fr_fr,
    name_subtext_lang_de_de,
    name_subtext_lang_en_cn,
    name_subtext_lang_en_tw,
    name_subtext_lang_es_es,
    name_subtext_lang_es_mx,
    name_subtext_lang_ru_ru,
    name_subtext_lang_ja_jp,
    name_subtext_lang_pt_pt,
    name_subtext_lang_it_it,
    name_subtext_lang_unknown_12,
    name_subtext_lang_unknown_13,
    name_subtext_lang_unknown_14,
    name_subtext_lang_unknown_15,
    name_subtext_lang_flags,
    description_lang_en_gb,
    description_lang_ko_kr,
    description_lang_fr_fr,
    description_lang_de_de,
    description_lang_en_cn,
    description_lang_en_tw,
    description_lang_es_es,
    description_lang_es_mx,
    description_lang_ru_ru,
    description_lang_ja_jp,
    description_lang_pt_pt,
    description_lang_it_it,
    description_lang_unknown_12,
    description_lang_unknown_13,
    description_lang_unknown_14,
    description_lang_unknown_15,
    description_lang_flags,
    aura_description_lang_en_gb,
    aura_description_lang_ko_kr,
    aura_description_lang_fr_fr,
    aura_description_lang_de_de,
    aura_description_lang_en_cn,
    aura_description_lang_en_tw,
    aura_description_lang_es_es,
    aura_description_lang_es_mx,
    aura_description_lang_ru_ru,
    aura_description_lang_ja_jp,
    aura_description_lang_pt_pt,
    aura_description_lang_it_it,
    aura_description_lang_unknown_12,
    aura_description_lang_unknown_13,
    aura_description_lang_unknown_14,
    aura_description_lang_unknown_15,
    aura_description_lang_flags,
    mana_cost_pct,
    start_recovery_category,
    start_recovery_time,
    max_target_level,
    spell_class_set,
    spell_class_mask_0,
    spell_class_mask_1,
    spell_class_mask_2,
    max_targets,
    defense_type,
    prevention_type,
    stance_bar_order,
    effect_chain_amplitude_0,
    effect_chain_amplitude_1,
    effect_chain_amplitude_2,
    min_faction_id,
    min_reputation,
    required_aura_vision,
    required_totem_category_id_0,
    required_totem_category_id_1,
    required_areas_id,
    school_mask,
    rune_cost_id,
    spell_missile_id,
    power_display_id,
    effect_bonus_coefficient_0,
    effect_bonus_coefficient_1,
    effect_bonus_coefficient_2,
    description_variables_id,
    difficulty
)
VALUES (
           360002, 1, 0, 0, 276824080,
           32, 0, 0, 0, 0, 0, 0,
           0, 0, 0, 0, 0, -1, 0, 0,
           0, 0, 0, 0, 0, 0, 0, 0,
           14, 0, 0, 31, 0, 0,
           0, 101, 0, 0, 1, 1,
           0, 3, 0, 0, 0, 0,
           1, 0, 0, 0,
           0, 0,
           0, 0, 0, 0, 0, 0, 0, 0,
           0, 0, 0, 0, 0, 0, 0, 0,
           -1, 0, 0,
           5, 0, 0,
           1, 0, 0,
           0, 0, 0,
           -1, 0, 0,
           0, 0, 0,
           1, 0, 0,
           17, 0, 0,
           0, 0, 0,
           0, 0, 0,
           0, 0, 0,
           0, 0, 0,
           0, 0, 0,
           0, 0, 0,
           0, 0, 0,
           0, 0, 0,
           0, 0, 0,
           0, 0, 0,
           0,0,0,
           0,0,0,
           0,0,0,
           220, 0,3807, 0, 0,
           'Trainers', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
           16712190,
           '','','','','',
           '','','','','',
           '','','','','',
           '',16712190,
           'Teleports you to the alliance trainers.',
           '','','','','','','',
           '','','','','','','',
           '',16712190,
           'Teleports you to the alliance trainers.','','','','',
           '','','','','','','',
           '','','','',
           16712190,
           0, 0, 0, 0, 0,
           0, 0, 0, 0, 0, 0, 0,
           1, 1, 1,
           0, 0, 0,
           0, 0, 0,
           0, 0, 0, 0,
           0, 0, 0,
           0, 0
       );

-- Create Horde Trainer Teleport spell
INSERT INTO spell (
    id,
    category,
    dispel_type,
    mechanic,
    attributes,
    attributes_ex,
    attributes_ex_b,
    attributes_ex_c,
    attributes_ex_d,
    attributes_ex_e,
    attributes_ex_f,
    attributes_ex_g,
    shapeshift_mask_0,
    shapeshift_mask_1,
    shapeshift_exclude_0,
    shapeshift_exclude_1,
    targets,
    target_creature_type,
    requires_spell_focus,
    facing_caster_flags,
    caster_aura_state,
    target_aura_state,
    exclude_caster_aura_state,
    exclude_target_aura_state,
    caster_aura_spell,
    target_aura_spell,
    exclude_caster_aura_spell,
    exclude_target_aura_spell,
    casting_time_index,
    recovery_time,
    category_recovery_time,
    interrupt_flags,
    aura_interrupt_flags,
    channel_interrupt_flags,
    proc_type_mask,
    proc_chance,
    proc_charges,
    max_level,
    base_level,
    spell_level,
    duration_index,
    power_type,
    mana_cost,
    mana_cost_per_level,
    mana_per_second,
    mana_per_second_per_level,
    range_index,
    speed,
    modal_next_spell,
    cumulative_aura,
    totem_0,
    totem_1,
    reagent_0,
    reagent_1,
    reagent_2,
    reagent_3,
    reagent_4,
    reagent_5,
    reagent_6,
    reagent_7,
    reagent_count_0,
    reagent_count_1,
    reagent_count_2,
    reagent_count_3,
    reagent_count_4,
    reagent_count_5,
    reagent_count_6,
    reagent_count_7,
    equipped_item_class,
    equipped_item_subclass,
    equipped_item_inv_types,
    effect_0,
    effect_1,
    effect_2,
    effect_die_sides_0,
    effect_die_sides_1,
    effect_die_sides_2,
    effect_real_points_per_level_0,
    effect_real_points_per_level_1,
    effect_real_points_per_level_2,
    effect_base_points_0,
    effect_base_points_1,
    effect_base_points_2,
    effect_mechanic_0,
    effect_mechanic_1,
    effect_mechanic_2,
    implicit_target_a_0,
    implicit_target_a_1,
    implicit_target_a_2,
    implicit_target_b_0,
    implicit_target_b_1,
    implicit_target_b_2,
    effect_radius_index_0,
    effect_radius_index_1,
    effect_radius_index_2,
    effect_aura_0,
    effect_aura_1,
    effect_aura_2,
    effect_aura_period_0,
    effect_aura_period_1,
    effect_aura_period_2,
    effect_amplitude_0,
    effect_amplitude_1,
    effect_amplitude_2,
    effect_chain_targets_0,
    effect_chain_targets_1,
    effect_chain_targets_2,
    effect_item_type_0,
    effect_item_type_1,
    effect_item_type_2,
    effect_misc_value_0,
    effect_misc_value_1,
    effect_misc_value_2,
    effect_misc_value_b_0,
    effect_misc_value_b_1,
    effect_misc_value_b_2,
    effect_trigger_spell_0,
    effect_trigger_spell_1,
    effect_trigger_spell_2,
    effect_points_per_combo_0,
    effect_points_per_combo_1,
    effect_points_per_combo_2,
    effect_spell_class_mask_a_0,
    effect_spell_class_mask_a_1,
    effect_spell_class_mask_a_2,
    effect_spell_class_mask_b_0,
    effect_spell_class_mask_b_1,
    effect_spell_class_mask_b_2,
    effect_spell_class_mask_c_0,
    effect_spell_class_mask_c_1,
    effect_spell_class_mask_c_2,
    spell_visual_id_0,
    spell_visual_id_1,
    spell_icon_id,
    active_icon_id,
    spell_priority,
    name_lang_en_gb,
    name_lang_ko_kr,
    name_lang_fr_fr,
    name_lang_de_de,
    name_lang_en_cn,
    name_lang_en_tw,
    name_lang_es_es,
    name_lang_es_mx,
    name_lang_ru_ru,
    name_lang_ja_jp,
    name_lang_pt_pt,
    name_lang_it_it,
    name_lang_unknown_12,
    name_lang_unknown_13,
    name_lang_unknown_14,
    name_lang_unknown_15,
    name_lang_flags,
    name_subtext_lang_en_gb,
    name_subtext_lang_ko_kr,
    name_subtext_lang_fr_fr,
    name_subtext_lang_de_de,
    name_subtext_lang_en_cn,
    name_subtext_lang_en_tw,
    name_subtext_lang_es_es,
    name_subtext_lang_es_mx,
    name_subtext_lang_ru_ru,
    name_subtext_lang_ja_jp,
    name_subtext_lang_pt_pt,
    name_subtext_lang_it_it,
    name_subtext_lang_unknown_12,
    name_subtext_lang_unknown_13,
    name_subtext_lang_unknown_14,
    name_subtext_lang_unknown_15,
    name_subtext_lang_flags,
    description_lang_en_gb,
    description_lang_ko_kr,
    description_lang_fr_fr,
    description_lang_de_de,
    description_lang_en_cn,
    description_lang_en_tw,
    description_lang_es_es,
    description_lang_es_mx,
    description_lang_ru_ru,
    description_lang_ja_jp,
    description_lang_pt_pt,
    description_lang_it_it,
    description_lang_unknown_12,
    description_lang_unknown_13,
    description_lang_unknown_14,
    description_lang_unknown_15,
    description_lang_flags,
    aura_description_lang_en_gb,
    aura_description_lang_ko_kr,
    aura_description_lang_fr_fr,
    aura_description_lang_de_de,
    aura_description_lang_en_cn,
    aura_description_lang_en_tw,
    aura_description_lang_es_es,
    aura_description_lang_es_mx,
    aura_description_lang_ru_ru,
    aura_description_lang_ja_jp,
    aura_description_lang_pt_pt,
    aura_description_lang_it_it,
    aura_description_lang_unknown_12,
    aura_description_lang_unknown_13,
    aura_description_lang_unknown_14,
    aura_description_lang_unknown_15,
    aura_description_lang_flags,
    mana_cost_pct,
    start_recovery_category,
    start_recovery_time,
    max_target_level,
    spell_class_set,
    spell_class_mask_0,
    spell_class_mask_1,
    spell_class_mask_2,
    max_targets,
    defense_type,
    prevention_type,
    stance_bar_order,
    effect_chain_amplitude_0,
    effect_chain_amplitude_1,
    effect_chain_amplitude_2,
    min_faction_id,
    min_reputation,
    required_aura_vision,
    required_totem_category_id_0,
    required_totem_category_id_1,
    required_areas_id,
    school_mask,
    rune_cost_id,
    spell_missile_id,
    power_display_id,
    effect_bonus_coefficient_0,
    effect_bonus_coefficient_1,
    effect_bonus_coefficient_2,
    description_variables_id,
    difficulty
)
VALUES (
           360003, 1, 0, 0, 276824080,
           32, 0, 0, 0, 0, 0, 0,
           0, 0, 0, 0, 0, -1, 0, 0,
           0, 0, 0, 0, 0, 0, 0, 0,
           14, 0, 0, 31, 0, 0,
           0, 101, 0, 0, 1, 1,
           0, 3, 0, 0, 0, 0,
           1, 0, 0, 0,
           0, 0,
           0, 0, 0, 0, 0, 0, 0, 0,
           0, 0, 0, 0, 0, 0, 0, 0,
           -1, 0, 0,
           5, 0, 0,
           1, 0, 0,
           0, 0, 0,
           -1, 0, 0,
           0, 0, 0,
           1, 0, 0,
           17, 0, 0,
           0, 0, 0,
           0, 0, 0,
           0, 0, 0,
           0, 0, 0,
           0, 0, 0,
           0, 0, 0,
           0, 0, 0,
           0, 0, 0,
           0, 0, 0,
           0, 0, 0,
           0,0,0,
           0,0,0,
           0,0,0,
           220, 0,3806, 0, 0,
           'Trainers', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
           16712190,
           '','','','','',
           '','','','','',
           '','','','','',
           '',16712190,
           'Teleports you to the horde trainers.',
           '','','','','','','',
           '','','','','','','',
           '',16712190,
           'Teleports you to the horde trainers.','','','','',
           '','','','','','','',
           '','','','',
           16712190,
           0, 0, 0, 0, 0,
           0, 0, 0, 0, 0, 0, 0,
           1, 1, 1,
           0, 0, 0,
           0, 0, 0,
           0, 0, 0, 0,
           0, 0, 0,
           0, 0
       );

insert into SkillLineAbility (id,skill_line,spell,race_mask,class_mask,exclude_race,exclude_class,min_skill_line_rank,superceded_by_spell,acquire_method,trivial_skill_line_rank_high,trivial_skill_line_rank_low,character_points_0,character_points_1)
values (21982,183,360002,1101,0,0,0,0,0,2,0,0,0,0);

insert into SkillLineAbility (id,skill_line,spell,race_mask,class_mask,exclude_race,exclude_class,min_skill_line_rank,superceded_by_spell,acquire_method,trivial_skill_line_rank_high,trivial_skill_line_rank_low,character_points_0,character_points_1)
values (21983,183,360003,690,0,0,0,0,0,2,0,0,0,0);

update spell set name_lang_en_gb = 'Trainers' where id in (360002,360003);

-- select name_lang_en_gb from spell where id in (360002,360003);